language: java
jdk: openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean test jacoco:report coveralls:report

notifications:
  email:
    recipients:
      - suloginscene@gmail.com
